# Generated by Django 6.0.2 on 2026-02-15 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('basin', models.CharField(max_length=200)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('operator', models.CharField(blank=True, max_length=200)),
                ('discovered', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeismicSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='seismic/')),
                ('inline_range', models.CharField(blank=True, max_length=50)),
                ('crossline_range', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seismic_surveys', to='core.field')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('well_type', models.CharField(choices=[('producer', 'Producer'), ('injector', 'Injector'), ('exploration', 'Exploration'), ('observation', 'Observation')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('drilling', 'Drilling'), ('shut-in', 'Shut-in'), ('abandoned', 'Abandoned')], default='drilling', max_length=20)),
                ('tvd', models.FloatField(blank=True, help_text='True Vertical Depth (m)', null=True)),
                ('md', models.FloatField(blank=True, help_text='Measured Depth (m)', null=True)),
                ('surface_lat', models.FloatField(blank=True, null=True)),
                ('surface_lon', models.FloatField(blank=True, null=True)),
                ('spud_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='core.field')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('doc_type', models.CharField(choices=[('report', 'Well Report'), ('seismic', 'Seismic Interpretation'), ('production', 'Production Report'), ('drilling', 'Drilling Report'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('content', models.TextField(blank=True, help_text='Extracted text content')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.field')),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.well')),
            ],
        ),
        migrations.CreateModel(
            name='WellLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Log name, e.g., GR, RHOB, NPHI', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('data', models.JSONField(default=dict, help_text='{depth: value}')),
                ('depth_min', models.FloatField(blank=True, null=True)),
                ('depth_max', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.well')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('oil_rate', models.FloatField(blank=True, help_text='Oil rate (m3/d)', null=True)),
                ('gas_rate', models.FloatField(blank=True, help_text='Gas rate (m3/d)', null=True)),
                ('water_rate', models.FloatField(blank=True, help_text='Water rate (m3/d)', null=True)),
                ('water_cut', models.FloatField(blank=True, help_text='Water cut (%)', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='Bottom hole pressure (bar)', null=True)),
                ('choke', models.FloatField(blank=True, help_text='Choke size (mm)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='core.well')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('well', 'date')},
            },
        ),
    ]
